name: Print PAT using PowerShell

on:
  workflow_dispatch:

jobs:
  print-pat:
    runs-on: Demo_runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script Inline
        shell: powershell
        run: |
          .\print-pat.ps1
