name: PAT Demo Workflow

on:
  workflow_dispatch:

jobs:
  use-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}   # Use your PAT instead of default GITHUB_TOKEN

      - name: Show masked token use
        run: |
          echo "Your PAT is securely stored and masked!"
          echo "Using the PAT, this workflow can access private repos or push code."

      - name: Add and push a new file using PAT
        run: |
          echo "Hello from PAT Demo Workflow at $(date)" > pat-demo.txt
          git config user.name "suresh"
          git config user.email "suresh@example.com"
          git add pat-demo.txt
          git commit -m "Added pat-demo.txt via GitHub Actions"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git HEAD:main
