name: Print PAT using PowerShell Script File

on:
  workflow_dispatch:

jobs:
  print-pat:
    runs-on: Demo_runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        run: powershell -NoProfile -ExecutionPolicy Bypass -File .\print-pat.ps1
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
