name: Print PAT using PowerShell

on:
  workflow_dispatch:

jobs:
  print-pat:
    runs-on: Demo_runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script Inline
        shell: pwsh
        run: |
          Write-Host "Running PowerShell Script..."
          $pat = "${{ secrets.MY_PAT }}"
          Write-Host "Your GitHub Personal Access Token is: $pat"
