name: Run PowerShell Script

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
jobs:
  run_script:
    runs-on: windows-latest  # Use the latest Windows runner for PowerShell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run HelloWorld.ps1 script
        run: |
          ./helloworld.ps1
